# Generated by Django 5.1.2 on 2024-11-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('tipoprod', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
    ]
