# Generated by Django 5.1.2 on 2024-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_sucursal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
