# Generated by Django 5.1 on 2024-11-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Id_empleado',
            new_name='codigo',
        ),
    ]
