# Generated by Django 5.1.2 on 2024-11-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0002_rename_id_empleado_empleado_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='puesto',
            new_name='sexo',
        ),
    ]
