# Generated by Django 5.1.2 on 2024-12-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0003_rename_puesto_empleado_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
    ]
