# Generated by Django 5.1.2 on 2024-12-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0004_remove_empleado_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_sucursal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
