# Generated by Django 5.1.2 on 2024-11-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
    ]
